- hosts: us-west-2a
  remote_user: ubuntu
  become: yes
  become_method: sudo
  tasks:
    - name: Update the Ubuntu system and services
      apt: update_cache=yes

    - name: Install Basic Unix-level Services
      apt: name={{ item }} state=latest
      with_items:
        - nginx
        - python3
        - python3-pip
        - python3.4-venv
        - git
        - gunicorn

    - name: Clone the Imager App to the Home Directory
      git: 
        clone=yes
        repo=https://github.com/adriennekarnoski/django-imager.git
        dest=/home/ubuntu/imagersite
        version=front-end-4

    - name: Create a virtual environment in the imager app repo
      command: python3 -m venv /home/ubuntu/imagersite/ENV

    # - name: Install all requirements for virtual environment
    #   pip: 
    #     virtualenv=/home/ubuntu/imagersite/ENV
    #     name={{ item }}
    #     with_items:
    #     - nginx
    #     - python3
    #     - python3-pip
    #     - python3.4-venv
    #     - git
    #     - gunicorn

    - name: Copy upstart script into /etc/init
      template: src=../templates/upstart_config dest=/etc/init/imagersite.conf
      
    - name: Restart the imagersite upstart job
      service: name=imagersite state=restarted
